[[main]]
  name = "Contact"
  url = "/contact"
  weight = 10

[[main]]
  name = "Service"
  identifier = "service"
  weight = 20

[[main]]
  name = "Analytics"
  parent = "service"
  url = "/analytics"
  weight = 10

[[main]]
  name = "AI"
  parent = "service"
  url = "/ai"
  weight = 20

[[main]]
  name = "Train"
  parent = "service"
  url = "/train"
  weight = 30

[[main]]
  name = "Scrape"
  parent = "service"
  url = "/scrape"
  weight = 40