baseURL = "http://www.exegetic.biz/"
languageCode = "en-us"
title = "exegetic"

theme = "exegetic"

[params]
  [params.contact]
    title = "Contact"
    text = ""
    [params.what.image]
      path = "https://via.placeholder.com/300"
      alt = "Watch"
    [params.how.image]
      path = "https://via.placeholder.com/300"
      alt = "Watch"
    [params.clients.image]
      path = "https://via.placeholder.com/300"
      alt = "Watch"
    [params.contact.image]
      path = "https://via.placeholder.com/300"
      alt = "Watch"
