baseURL = "https://www.exegetic.biz/"
languageCode = "en-us"
title = "exegetic"

theme = "exegetic"

[params]
  [params.contact]
    title = "Contact"
    text = ""
  [params.about]
    [params.about.image]
      path = "img/exegetic-logo.svg"
      alt = "Watch"
  [params.what]
    [params.what.image]
      path = "img/exegetic-logo.svg"
      alt = "Watch"
  [params.how]
    [params.how.image]
      path = "img/exegetic-logo.svg"
      alt = "Watch"
  [params.clients]
    [params.clients.image]
      path = "https://via.placeholder.com/300"
      alt = "Watch"
